FROM jinhasong/alphapose:cuda-11.6_abd

ENV TZ Asia/Seoul
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get -y install \
    python3 python3-pip python3-dev \
    libgl1 \
    tzdata git wget ssh vim

RUN ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
RUN echo "root:password" | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes #prohibit-password/' /etc/ssh/sshd_config

RUN pip3 install --upgrade pip
RUN pip3 install setuptools

WORKDIR /workspace
RUN mkdir -p /workspace/weights
RUN wget ftp://mldisk.sogang.ac.kr/cctv/weights/yolov7-obstacle/yolov7x.pt -P /workspace/weights
RUN wget ftp://mldisk.sogang.ac.kr/cctv/weights/alphapose/halpe_26_fast_res50_256x192.pth -P /workspace/weights
